### ISSUE TITLE
Question: what is the meaning of mp1 and mp2 and the index_s and index_h files?

### ISSUE THREAD

**Issue by tarngerine** [tomohxx/shanten-number#1]
Hi, this is a really cool project and I am learning a lot. Thank you for sharing it publicly.

I have a question: I am not able to understand the purpose of `mp1` and `mp2`, which both refer to the last line (e.g. 1953125/78125 for the files `index_s` and `index_h` respectively).

1. What does "mp1" and "mp2" mean? 
2. What are the numbers in these 2 files?

Thank you for your time. ありがとうございます

**Comment by tarngerine** [comment]
I understand they are preprocessed to help the speed of calculation, but the contents are mystifying to me. It looks like for every hand in `index_h` there are 25 rows of 10 numbers in `index_s`

**Comment by tomohxx** [comment]
The variables `mp1` and `mp2` means "map" from hand to distance table, which are the number of tiles required to make winning hand (和了形).

A hand consisting only of suit tiles (数牌) has 5^9 ways, and a hand consisting only of hounor tiles (字牌) has 5^7 ways. These are the number of lines in the files `index_s.txt` and `index_h.txt`.

See the page below for details (Japanese).
- https://qiita.com/tomohxx/items/75b5f771285e1334c0a5
- https://tomohxx.github.io/mahjong-algorithm-book/ssrf/
